### ISSUE TITLE
Dropdown issues

### ISSUE THREAD

**Issue by hamdano2** [qwikerx/flowbite-qwik#188]
Hi.
I found a handful of problems with the Dropdown component.

1. How documentation makes dropdown dioes not work. It throws an error Suffics attribute has unexpected type qcomponent.

<Dropdown label="Actions"> does not work.
But doing it like this does.      <Dropdown as={<Button>Actions</Button>} class="static" >
2. It added bullet points in front of each menu item which is not expected.

**Comment by xmimiex** [comment]
Hi hamdano2, thanks for taking the time to test flowbite-qwik and for leaving a bug report.
However, we are having trouble understanding your issue. Could you please write a snippet of code and provide the version of the library you are using?
Thank you.

**Comment by hamdano2** [comment]
Hi @xmimiex 
thanks for your message. I will try again. The way that the documentation recommends to make drop down does not work in latest version of library.
``` tsx
<DropDown label="actions" >
```
it throws an error about suffix not being a function.

I did find a work around. 
``` tsx
<Dropdown as={<Buttion>Actions</Button>} class="static" >
```

**Comment by hamdano2** [comment]
Halso I found other issues with dropdown.
1. It makes bullet symbols infront of each menu item which is not excpected by me.
2. And I found the placement of the menu not what I expected I expected it to be below, not above the button.

**Comment by xmimiex** [comment]
I just tried this simple code and it works like a charm, I use version 0.36.1

```
<Dropdown label="Actions">
          <Dropdown.Item>A1</Dropdown.Item>
          <Dropdown.Item>A2</Dropdown.Item>
          <Dropdown.Item>A3</Dropdown.Item>
        </Dropdown>
```

![image](https://github.com/user-attachments/assets/fc34b6c1-45f7-4ae3-9e2e-140fe03ad859)

I think you have a misconfiguration in your global.css or tailwind.config.js.

My global.css file includes this on top :

```
@tailwind base;
@tailwind components;
@tailwind utilities;

...
```

My tailwind.config.js file : 

```
import flowbitePlugin from 'flowbite/plugin'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['node_modules/flowbite-qwik/**/*.{cjs,mjs}', './src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      animation: {
        'from-left': 'slideFromLeft 0.2s 1',
        'from-right': 'slideFromRight 0.2s 1',
      },
      keyframes: {
        slideFromLeft: {
          '0%': {
            transform: 'translateX(-100%)',
          },
          '100%': {
            transform: 'translateX(0)',
          },
        },
        slideFromRight: {
          '0%': {
            transform: 'translateX(100%)',
          },
          '100%': {
            transform: 'translateX(0)',
          },
        },
      },
    },
  },
  plugins: [flowbitePlugin],
}

```

**Comment by hamdano2** [comment]
Hi. Thanks @xmimiex . That fixed the problem. I used the automatic installer before to set it up, but, it looks like their was an error. I also was missing postcss and it wasn't installed properly. 
But this is good now.
