### ISSUE TITLE
DatePicker issues

### ISSUE THREAD

**Issue by fraz666** [qwikerx/flowbite-qwik#197]
Hello!

I'm getting the error **"Code(3): Only primitive and object literals can be serialized"** when trying to use the **DatePicker** component.

To replicate the issue, you can create a new project with the command `npm create qwik@latest`, install the library with `npx flowbite-qwik-cli@latest init` and add the DatePicker in the default `index.tsx` file.

```js
export default component$(() => {
  return (
    <>
      <h1>Hi 👋</h1>
      <DatePicker ></DatePicker >
      <div>
        Can't wait to see what you build with qwik!
        <br />
        Happy coding.
      </div>
    </>
  );
});
```

![image](https://github.com/user-attachments/assets/9e77a6ab-98f7-4cac-95ab-b07ae8080222)

Using node 22.8.0 and npm 10.8.2

Am I missing something?
Thank you for your time

**Comment by xmimiex** [comment]
Hi @fraz666 , I am not sure but I think we miss some information in the setup configuration, can you add the dependency to flowbite-qwik-icons in your package.json please ? And tell me if it fixes.

**Comment by fraz666** [comment]
Hi @xmimiex!
Installing the `flowbite-qwik-icons` as a dev dependency fixed the issue.
Thank you very much

**Comment by xmimiex** [comment]
ok cool, the documentation has been updated : https://github.com/qwikerx/flowbite-qwik/pull/198
