### ISSUE TITLE
Official vs Unofficial

### ISSUE THREAD

**Issue by lbensaad** [qwikerx/flowbite-qwik#199]
In this github repository the about section says: `Unofficial Qwik components built for Flowbite and Tailwind CSS` but on the web site [flowbite-qwik.com](https://flowbite-qwik.com/) it says: `Flowbite Qwik is an official Flowbite component library for Qwik.`
Please clarify which of is correct!

**Comment by jcfauchet** [comment]
Hi @lbensaad 
Thank you for your feedback. We overlooked updating 'Unofficial' to 'Official' throughout. This will be addressed in the next PR.
