### ISSUE TITLE
Breadcrumb RTL issue

### ISSUE THREAD

**Issue by lbensaad** [qwikerx/flowbite-qwik#200]
The direction of the arrows of the [Breadcrumb](https://flowbite-qwik.com/docs/components/breadcrumb) in RTL is incorrect. They are going from left to right, but they should be going from right to left

**Comment by jcfauchet** [comment]
Hi @lbensaad 
Nice catch! Thank you for pointing out this issue. It will be fixed in the next release.
Regards
