### ISSUE TITLE
DatePicker can't be closed on click outside

### ISSUE THREAD

**Issue by genox** [qwikerx/flowbite-qwik#206]
Hi,

Currently, the date picker only seems to be closable by choosing a value. I think it should also be closable by clicking outside, e.g. using a `useClickOutside()`.

Thanks!

**Comment by xmimiex** [comment]
Hi @genox , yes you are right, we'll add this.

**Comment by xmimiex** [comment]
Hi @genox , you can test with the latest version, v0.37.8.
Examples : https://flowbite-qwik.com/docs/components/date-picker
