### ISSUE TITLE
Unable to set font size on <Input/>

### ISSUE THREAD

**Issue by genox** [qwikerx/flowbite-qwik#208]
Hi,

When trying to make a large `Input` field using `size="lg"` I would like to adjust the font-size as well. Using `class="text-lg"` on the `Input` has no effect because the actual <input/> element has `text-sm` applied, which takes precedence over the class on the parent. There seems to be also no easy way to target the input directly using arbitrary selectors.

I think either an exposed text-size attribute on the component or a theme option would be nice.

Best regards!

**Comment by xmimiex** [comment]
Hi @genox, yes I will add a "theme" option, I'll keep you informed.

**Comment by xmimiex** [comment]
Hey @genox , latest version fixes this issue, v0.37.8

**Comment by genox** [comment]
Thank you, I've seen the commit. I discovered an issue win my PR that I made recently, I will push a fix for that too.

**Comment by xmimiex** [comment]
I think we have fixed your discovered issue, you can test before with the latest version.

Documentation for modular-forms : https://flowbite-qwik.com/docs/forms/input#modular-forms

**Comment by genox** [comment]
I noticed that input in some cases didn't fire onChange$ or did so with a huge delay.

I also noticed that my typing of those qwik attributes was wrong. I will check if this is changed or make a PR.

**Comment by genox** [comment]
After your revert, my form no longer receives change events and the data is not logged in the formAction$ anymore. 

I guess this also depends on the complexity of the form, as well as how deeply nested the form is. Otherwise I can't explain this behaviour. The only thing that helped for me was **to not spread props that contain qwik events or signals**.
