### ISSUE TITLE
NavBarPage cannot be found

### ISSUE THREAD

**Issue by st-clair-clarke** [qwikerx/flowbite-qwik#211]
Hi, ALL THE 'Edit on GitHub' LINKS ARE BROKEN!

I am trying to use the following - [sidebar-with-navbar](https://flowbite-qwik.com/docs/components/sidebar#sidebar-with-navbar)

The NavbarPage cannot be found and the example link does not work.

Could I have a working example please?

Thanks

**Comment by xmimiex** [comment]
Hi @st-clair-clarke , we will fix example links as soon as possible, but all code example are just under the preview in the website : 
![image](https://github.com/user-attachments/assets/3c83e92b-9238-4703-adf7-ee9e32201f40)

**Comment by st-clair-clarke** [comment]
Thanks for your 'qwik' reply. But in the specific example above, I cannot import the component **NavbarPage** that is being used to host the SideBar component.

**Comment by xmimiex** [comment]
example code is here : https://github.com/qwikerx/flowbite-qwik/blob/main/apps/web/src/routes/examples/%5Btheme-rtl%5D/sidebar/04-sidebar-with-navbar/index.tsx

NavbarPage example is here : https://github.com/qwikerx/flowbite-qwik/blob/main/apps/web/src/components/NavbarPage/NavbarPage.tsx
