### ISSUE TITLE
Navbar with dropdown not working on mobile

### ISSUE THREAD

**Issue by lukemansell** [qwikerx/flowbite-qwik#217]
Hiya. 

On a mobile breakpoint, the Navbar with dropdown doesn't work as expected. This also occurs on your documentation page too here: https://flowbite-qwik.com/docs/components/navbar#navbar-with-dropdown

If you press the mobile icon, then click "Services" the dropdown doesn't display, it just closes the nav-bar menu.

Can repo on Chrome and Firefox.

**Comment by jcfauchet** [comment]
Hi @lukemansell ,

Thanks for your issue! I was able to reproduce the behavior you mentioned.

We’ll review it and work on a fix for the next release.
